In [1]:
import numpy as np

In [2]:
a = np.array([2,3,4]) # 넘파이 ndarray 객체 생성
# a 객체의 형상(shape), 차원, 요소의 자료형, 요소의 크기(byte), 요소의 수
a.shape, a.ndim, a.dtype, a.size

((3,), 1, dtype('int32'), 3)

In [3]:
b = np.array([[1,2,3], [4,5,6]]) # 넘파이 2차원 ndarray
b.shape

(2, 3)

In [4]:
a = np.array([10, 20, 30])
b = np.array([1, 2, 3])

In [5]:
a + b

array([11, 22, 33])

In [6]:
a - b

array([ 9, 18, 27])

In [7]:
a * b

array([10, 40, 90])

In [8]:
a / b

array([10., 10., 10.])

In [9]:
a = np.array([10, 20, 30])
a * 10

array([100, 200, 300])

In [10]:
a + 10

array([20, 30, 40])

In [11]:
b = np.array([[10, 20, 30],
              [40, 50, 60]])
c = np.array([2, 3, 4])

In [12]:
b + c

array([[12, 23, 34],
       [42, 53, 64]])

In [13]:
b * c

array([[ 20,  60, 120],
       [ 80, 150, 240]])

In [14]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [16]:
np.arange(0, 10, 3)

array([0, 3, 6, 9])

In [17]:
np.arange(0.0, 1.0, 0.2)

array([0. , 0.2, 0.4, 0.6, 0.8])

In [18]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [19]:
np.linspace(0, 10, 4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [20]:
# end